class Gitmole < Formula
  include Language::Python::Virtualenv

  desc "Offline git repository analysis with a terminal report"
  homepage "https://github.com/antvinni/gitmole"
  url "https://github.com/antvinni/gitmole/releases/download/v0.2.2/gitmole-0.2.2.tar.gz"
  sha256 "a3d4af49711f816860110407b0e5fb28afc92fd7e26d0e22cbf3f7fb840c3e23"
  license "MIT"
  head "https://github.com/antvinni/gitmole.git", branch: "main"

  depends_on "git-sizer"
  depends_on "gitleaks"
  depends_on "python@3.14"
  depends_on "scc"

  # resources: generated by `brew update-python-resources antvinni/gitmole/gitmole`

  def install
    virtualenv_install_with_resources
  end

  test do
    assert_match "gitmole #{version}", shell_output("#{bin}/gitmole --version")
    system "git", "init", "-q", "repo"
    (testpath/"repo/a.py").write "x = 1\n"
    system "git", "-C", "repo", "add", "a.py"
    system "git", "-C", "repo", "-c", "user.name=t", "-c", "user.email=t@x", "commit", "-q", "-m", "one"
    output = shell_output("#{bin}/gitmole repo --out out --markdown - 2>/dev/null")
    assert_match "1 commits", output
  end
end
